# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1439391671);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1439391838);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 3);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 29);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.reader.detectedFirstArticle", true);
user_pref("browser.rights.3.shown", true);
user_pref("browser.search.countryCode", "CA");
user_pref("browser.search.region", "CA");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20150806001005");
user_pref("browser.slowStartup.averageTime", 1554);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20150806001005");
user_pref("browser.startup.homepage_override.mstone", "39.0.3");
user_pref("browser.syncPromoViewsLeftMap", "{\"addons\":4,\"passwords\":4}");
user_pref("browser.taskbar.lastgroupid", "E7CF176E110C211B");
user_pref("browser.toolbarbuttons.introduced.pocket-button", true);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"PanelUI-contents\":[\"edit-controls\",\"zoom-controls\",\"new-window-button\",\"privatebrowsing-button\",\"save-page-button\",\"print-button\",\"history-panelmenu\",\"fullscreen-button\",\"find-button\",\"preferences-button\",\"add-ons-button\",\"developer-button\"],\"addon-bar\":[\"addonbar-closebutton\",\"status-bar\"],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"urlbar-container\",\"search-container\",\"bookmarks-menu-button\",\"pocket-button\",\"downloads-button\",\"home-button\",\"loop-button\",\"greasemonkey-tbb\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\"],\"currentVersion\":4,\"newElementCount\":0}");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1439477951356");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1439391613471");
user_pref("datareporting.policy.firstRunTime", "1439391551356");
user_pref("datareporting.sessions.current.activeTicks", 1);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.main", 40);
user_pref("datareporting.sessions.current.startTime", "1439391890293");
user_pref("datareporting.sessions.current.totalTime", 4);
user_pref("datareporting.sessions.currentIndex", 2);
user_pref("datareporting.sessions.previous.0", "{\"s\":1439391551025,\"a\":6,\"t\":163,\"c\":true,\"m\":36,\"fp\":2099,\"sr\":2423}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1439391717180,\"a\":13,\"t\":161,\"c\":true,\"m\":0,\"fp\":1037,\"sr\":1222}");
user_pref("dom.mozApps.used", true);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "%7Be4a8a97b-f2ed-450b-b12d-ee082ba24781%7D:3.3,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:39.0.3");
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.greasemonkey.haveInsertedToolbarbutton", true);
user_pref("extensions.greasemonkey.menuCommanderEventNameSuffix", "SAYSZ66ZW4CQCRFYOJRLZFANOJLL27DJ");
user_pref("extensions.greasemonkey.stats.prompted", true);
user_pref("extensions.greasemonkey.version", "3.3");
user_pref("extensions.lastAppVersion", "39.0.3");
user_pref("extensions.lastPlatformVersion", "39.0.3");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("extensions.xpiState", "{\"app-profile\":{\"{e4a8a97b-f2ed-450b-b12d-ee082ba24781}\":{\"d\":\"C:\\\\Users\\\\christopher.wong\\\\Documents\\\\Automation\\\\FF Profile\\\\extensions\\\\{e4a8a97b-f2ed-450b-b12d-ee082ba24781}.xpi\",\"e\":true,\"v\":\"3.3\",\"st\":1439391717457}},\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"C:\\\\Program Files (x86)\\\\Mozilla Firefox\\\\browser\\\\extensions\\\\{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"39.0.3\",\"st\":1438961842364,\"mt\":1438853260000}}}");
user_pref("gecko.buildID", "20150806001005");
user_pref("gecko.mstone", "39.0.3");
user_pref("gfx.direct3d.last_used_feature_level_idx", 0);
user_pref("media.gmp-eme-adobe.lastUpdate", 1439391619);
user_pref("media.gmp-eme-adobe.version", "12");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1439391619);
user_pref("media.gmp-gmpopenh264.version", "1.4");
user_pref("media.gmp-manager.buildID", "20150806001005");
user_pref("media.gmp-manager.lastCheck", 1439391613);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1439391890);
user_pref("toolkit.telemetry.previousBuildID", "20150806001005");
